name: "NuGet"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PACKAGE_PROJECT: "./Autofac.Extensions.DependencyInjection.AzureFunctions/Autofac.Extensions.DependencyInjection.AzureFunctions.csproj"
  BUILD_PLATFORM: 'Any CPU'
  BUILD_CONFIGURATION: 'Release'
  PUBLISH_DIR: "../publish"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: "Get Commit Date"
        uses: actions/github-script@0.3.0
        id: author-date
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |             
            const commit_details = await github.git.getCommit({owner: context.repo.owner, repo: context.repo.repo, commit_sha: context.sha});
            return commit_details.data.author.date
            
      - name: "Set Version Number"
        run: |
          echo "::set-env name=VERSION_NUMBER::$(date -d ${{ steps.author-date.outputs.result }} +%Y.%m.%d.%H%M)";
          PACKAGE_VERSION=$(cat "$PACKAGE_PROJECT" | grep -oPm1 "(?<=<PackageVersion>)[^<]+")
          echo "::set-env name=PACKAGE_VERSION::$PACKAGE_VERSION.${{ github.run_number }}";

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
        with:
          nuget-version: "latest"
          nuget-api-key: ""

      - name: NuGet Restore
        run: nuget restore

      - name: Build
        run: msbuild -p:Configuration="$BUILD_CONFIGURATION" -p:Platform="$BUILD_PLATFORM" -m -p:GeneratePackageOnBuild=true -p:OutDir=$PUBLISH_DIR -p:Version=$VERSION_NUMBER -p:AssemblyVersion=$VERSION_NUMBER -p:AssemblyInformationalVersion=$VERSION_NUMBER -p:GenerateProjectSpecificOutputFolder=true
        
      - name: Publish Package
        id: "publish"
        if: github.ref == 'refs/heads/master'
        run: echo "Publish Test ${{ env.PACKAGE_VERSION }}"; ls $PUBLISH_DIR;
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        if: steps.publish.status == success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ env.PACKAGE_VERSION }}
          body: |
            Changes in this Release
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
          

